spring:
  h2:
    console:
      enabled: true # wlacza przegledarke bazy: http://localhost:8080/h2-console
  datasource:
    url: jdbc:h2:file:~/.aplikacja-webowa/database.db;AUTO_SERVER=TRUE
    username: sa # Mozna zmienic, ale chyba nieistotne
    password: "" # Mozna zmienic, ale chyba nieistotne
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
